// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4SXTC_B8DXb-mwXO1_AG4cDrE8XMzvU',
    appId: '1:774007259454:web:5db00325dcfc6168c76c6f',
    messagingSenderId: '774007259454',
    projectId: 'olx-clone-flutter-f4be8',
    authDomain: 'olx-clone-flutter-f4be8.firebaseapp.com',
    storageBucket: 'olx-clone-flutter-f4be8.appspot.com',
    measurementId: 'G-CK45SQJPND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpG_baxBgjaAdBdGFb7vPGRBuT5L8FqFY',
    appId: '1:774007259454:android:976aa7c4bb9e51aac76c6f',
    messagingSenderId: '774007259454',
    projectId: 'olx-clone-flutter-f4be8',
    storageBucket: 'olx-clone-flutter-f4be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LhAVXUqHackltUmrOSQULMaVB4aMugE',
    appId: '1:774007259454:ios:f268be1260c5b01ec76c6f',
    messagingSenderId: '774007259454',
    projectId: 'olx-clone-flutter-f4be8',
    storageBucket: 'olx-clone-flutter-f4be8.appspot.com',
    androidClientId: '774007259454-bvdatsoc88ogfjp13b9sjiehmte9b5hr.apps.googleusercontent.com',
    iosClientId: '774007259454-mf9iedrf6ku86n3d4l4gqb0ag274q8o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LhAVXUqHackltUmrOSQULMaVB4aMugE',
    appId: '1:774007259454:ios:f268be1260c5b01ec76c6f',
    messagingSenderId: '774007259454',
    projectId: 'olx-clone-flutter-f4be8',
    storageBucket: 'olx-clone-flutter-f4be8.appspot.com',
    androidClientId: '774007259454-bvdatsoc88ogfjp13b9sjiehmte9b5hr.apps.googleusercontent.com',
    iosClientId: '774007259454-mf9iedrf6ku86n3d4l4gqb0ag274q8o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxClone',
  );
}
